//! Which slots a hull has and what fits in each — the game's outfitting
//! facts, so a build can be planned on a ship the commander does not own
//! yet and a module can be swapped without offering one the slot refuses
//! (maintainer, 2026-09-20: "for the ships we'll have to actually build
//! in their exact slotting and what module types can go where").
//!
//! The tables are `data/ship_slots.json` (per hull: every slot with the
//! journal's own name, its size, and what it takes) and
//! `data/module_kinds.json` (per module symbol: its kind, class, the
//! hulls it is bound to, and how many a ship may carry). Both are
//! generated by `docs/benches/knobs/gen_ship_slots.py` and pinned against
//! the vendored Coriolis sizes and the maintainer's own journal Loadouts
//! (`docs/benches/2026-09-20-ship-slots-pin.csv`: every fitted slot of
//! twelve ships named in the table). The slot NAMES matter: the journal
//! numbers a hull's internals with gaps (the Anaconda has no Slot11 or
//! Slot12; the Type-10's Slot11 comes after its two military slots), so
//! they are per-hull facts, not a rule.
//!
//! The rules, in order: the slot's own list of kinds when it has one
//! (core slots, military slots, the Type-11's mining hardpoints and
//! limpet slot, the Panther's cargo slots, the Caspian's cabins), else
//! the slot family's kinds; class no larger than the slot; life support,
//! sensors and the SCO drives exactly the slot's size; a hull-bound
//! module (fighter hangars, luxury cabins, the Panther's Mk II racks)
//! only on its hulls.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::collections::HashMap;

/// One slot of a hull.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Slot {
    /// The journal's `Slot` value (`Slot11_Size2`, `Military01`, `LargeHardpoint1`, `PowerPlant`).
    pub slot: String,
    /// hardpoint | utility | core | military | internal
    pub group: String,
    /// 0 for utility mounts; 1..=8 otherwise.
    pub size: i64,
    /// Kinds this slot takes, when it is narrower than its family.
    #[serde(default)]
    pub only: Vec<String>,
    /// The module must be exactly the slot's size (life support, sensors).
    #[serde(default)]
    pub exact_size: bool,
}

#[derive(Debug, Clone, Deserialize)]
struct HullRaw {
    name: String,
    slots: Vec<Slot>,
    #[serde(default)]
    stock: HashMap<String, String>,
}

/// A hull: its slots and its stock fit.
#[derive(Debug, Clone, Serialize)]
pub struct Hull {
    /// The journal's ship symbol, lowercase (`type9_military`).
    pub symbol: String,
    /// The printed name ("Type-10 Defender").
    pub name: String,
    pub slots: Vec<Slot>,
    /// Slot -> module symbol as the ship is sold.
    pub stock: HashMap<String, String>,
}

impl Hull {
    pub fn slot(&self, name: &str) -> Option<&Slot> {
        self.slots.iter().find(|s| s.slot.eq_ignore_ascii_case(name))
    }
}

/// What kind of thing a module symbol is.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModuleKind {
    /// The kind code (`hpl` pulse lasers, `icr` cargo racks, `cfsdo` SCO drives, ...).
    pub kind: String,
    pub class: i64,
    pub rating: String,
    /// The kind's printed name ("Pulse Laser", "Cargo Rack").
    pub name: String,
    #[serde(default)]
    pub mount: Option<String>,
    /// Hulls this module is sold for, when it is bound to some (fighter
    /// hangars, luxury cabins, Mk II racks); empty means every hull.
    #[serde(default)]
    pub ships: Vec<String>,
    /// How many a ship may carry, when limited (one shield generator, one hangar, ...).
    #[serde(default)]
    pub limit: Option<i64>,
    /// Must be exactly the slot's size (SCO drives).
    #[serde(default)]
    pub exact_size: bool,
}

/// The kinds each slot family takes.
fn family_kinds(group: &str) -> &'static [&'static str] {
    match group {
        "hardpoint" => &["hel", "hul", "hc", "hex", "hexxm", "hexxc", "hexgg", "hexgp", "hexgs", "hexsc", "hextp", "hfc", "hm", "hmtl", "hmtm", "hmr", "hmc", "hpa", "hpl", "hrg", "htp"],
        "utility" => &["ucl", "uec", "uex", "uhsl", "ukws", "ucs", "upd", "upwa", "usb", "ufsws"],
        "military" => &["ihrp", "isrp", "imahrp", "imrp", "iscb"],
        "internal" => &[
            "iafmu", "icr", "iclc", "idlc", "iex", "ifh", "ifa", "ifsdb", "ifsdi", "ifs", "cft", "iftlc", "ihblc", "ihrp", "isrp", "imahrp", "imrp", "imlc", "ipc", "ipvh", "iplc", "inlc", "ir",
            "irlc", "islc", "iscb", "isg", "iss", "ipas",
        ],
        _ => &[],
    }
}

pub struct Slots {
    hulls: HashMap<String, Hull>,
    kinds: HashMap<String, ModuleKind>,
}

impl Slots {
    pub fn load() -> Self {
        let raw: HashMap<String, HullRaw> = serde_json::from_str(include_str!("../data/ship_slots.json")).expect("ship_slots.json parses");
        let hulls = raw
            .into_iter()
            .map(|(symbol, h)| {
                let stock = h.stock.into_iter().map(|(k, v)| (k, v.to_ascii_lowercase())).collect();
                (symbol.clone(), Hull { symbol, name: h.name, slots: h.slots, stock })
            })
            .collect();
        let kinds = serde_json::from_str(include_str!("../data/module_kinds.json")).expect("module_kinds.json parses");
        Slots { hulls, kinds }
    }

    /// By the journal's ship symbol or the printed name.
    pub fn hull(&self, symbol_or_name: &str) -> Option<&Hull> {
        let key = symbol_or_name.to_ascii_lowercase();
        self.hulls.get(&key).or_else(|| self.hulls.values().find(|h| h.name.eq_ignore_ascii_case(symbol_or_name)))
    }

    /// Every hull, by printed name.
    pub fn hulls(&self) -> Vec<&Hull> {
        let mut v: Vec<&Hull> = self.hulls.values().collect();
        v.sort_by(|a, b| a.name.cmp(&b.name));
        v
    }

    pub fn kind(&self, item: &str) -> Option<&ModuleKind> {
        self.kinds.get(&item.to_ascii_lowercase())
    }

    /// Whether `item` may go in `slot` of `hull`; the reason when not, as
    /// the commander reads it.
    pub fn fits(&self, hull: &Hull, slot: &Slot, item: &str) -> Result<(), String> {
        let Some(k) = self.kind(item) else { return Err(format!("{} is not a module the outfitting tables know", ed_journal::modules::item_name(item))) };
        let allowed: Vec<&str> = if slot.only.is_empty() { family_kinds(&slot.group).to_vec() } else { slot.only.iter().map(String::as_str).collect() };
        if !allowed.iter().any(|a| *a == k.kind) {
            return Err(format!("{} does not take a {}", ed_journal::modules::slot_name(&slot.slot), k.name.to_ascii_lowercase()));
        }
        if k.class > slot.size {
            return Err(format!("class {} is too large for {} (size {})", k.class, ed_journal::modules::slot_name(&slot.slot), slot.size));
        }
        if (slot.exact_size || k.exact_size) && k.class != slot.size {
            return Err(format!("{} takes exactly class {}", ed_journal::modules::slot_name(&slot.slot), slot.size));
        }
        if !k.ships.is_empty() && !k.ships.iter().any(|s| s.eq_ignore_ascii_case(&hull.symbol)) {
            return Err(format!("{} is not sold for the {}", ed_journal::modules::item_name(item), hull.name));
        }
        // Hull-bound racks and limpet controllers go in the slots named for them.
        if !k.ships.is_empty() {
            let upper = slot.slot.to_ascii_uppercase();
            if k.kind == "icr" && !upper.starts_with("CARGO") {
                return Err(format!("{} goes in a cargo slot", ed_journal::modules::item_name(item)));
            }
            if k.kind == "imlc" && !upper.starts_with("LIMPETCONTROLLER") {
                return Err(format!("{} goes in the limpet controller slot", ed_journal::modules::item_name(item)));
            }
        }
        Ok(())
    }

    /// Every module that fits `slot` of `hull`: by kind name, then class
    /// (largest first), then rating.
    pub fn candidates(&self, hull: &Hull, slot: &Slot) -> Vec<(&str, &ModuleKind)> {
        let mut out: Vec<(&str, &ModuleKind)> = self.kinds.iter().filter(|(item, _)| self.fits(hull, slot, item).is_ok()).map(|(item, k)| (item.as_str(), k)).collect();
        out.sort_by(|a, b| a.1.name.cmp(&b.1.name).then(b.1.class.cmp(&a.1.class)).then(a.1.rating.cmp(&b.1.rating)).then(a.1.mount.cmp(&b.1.mount)));
        out
    }

    /// Modules a ship may carry only so many of: "two shield generators"
    /// and the like, over the whole fit (fitted plus swapped).
    pub fn over_limit(&self, items: &[(String, String)]) -> Vec<String> {
        let mut count: HashMap<&str, (i64, &ModuleKind)> = HashMap::new();
        for (_, item) in items {
            if let Some(k) = self.kind(item) {
                if k.limit.is_some() {
                    count.entry(k.kind.as_str()).or_insert((0, k)).0 += 1;
                }
            }
        }
        let mut out: Vec<String> = count
            .values()
            .filter(|(n, k)| Some(*n) > k.limit)
            .map(|(n, k)| format!("{n} × {}: a ship carries at most {}", k.name.to_ascii_lowercase(), k.limit.unwrap_or(0)))
            .collect();
        out.sort();
        out
    }

    /// The hull as sold, shaped like a journal `Loadout`, so every reader
    /// of a Loadout (figures, plan, import, SLEF) works on a ship the
    /// commander does not have yet.
    pub fn stock_loadout(&self, hull: &Hull) -> Value {
        let mut modules = Vec::new();
        let mut fuel = 0.0;
        let mut cargo = 0i64;
        for s in &hull.slots {
            let Some(item) = hull.stock.get(&s.slot) else { continue };
            if let Some(k) = self.kind(item) {
                match k.kind.as_str() {
                    "cft" if s.slot == "FuelTank" => fuel = (1i64 << k.class) as f64,
                    "icr" => cargo += 1i64 << k.class,
                    _ => {}
                }
            }
            modules.push(json!({ "Slot": s.slot, "Item": item, "On": true, "Priority": 1 }));
        }
        modules.push(json!({ "Slot": "ShipCockpit", "Item": format!("{}_cockpit", hull.symbol), "On": true, "Priority": 1 }));
        modules.push(json!({ "Slot": "CargoHatch", "Item": "modularcargobaydoor", "On": true, "Priority": 2 }));
        json!({
            "event": "Loadout",
            "Ship": hull.symbol,
            "Ship_Localised": hull.name,
            "ShipID": Value::Null,
            "ShipName": "",
            "ShipIdent": "",
            "Stock": true,
            "FuelCapacity": { "Main": fuel, "Reserve": 0.0 },
            "CargoCapacity": cargo,
            "Modules": modules,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn slots() -> Slots {
        Slots::load()
    }

    #[test]
    fn the_type_10_has_the_journals_own_slot_names() {
        let s = slots();
        let h = s.hull("type9_military").unwrap();
        assert_eq!(h.name, "Type-10 Defender");
        // The journal skips 9 and 10 (the military slots): pinned against the maintainer's Loadout.
        let internals: Vec<&str> = h.slots.iter().filter(|x| x.group == "internal").map(|x| x.slot.as_str()).collect();
        assert_eq!(internals, ["Slot01_Size8", "Slot02_Size7", "Slot03_Size6", "Slot04_Size5", "Slot05_Size4", "Slot06_Size4", "Slot07_Size3", "Slot08_Size3", "Slot11_Size2", "Slot12_Size1", "PlanetaryApproachSuite"]);
        assert_eq!(h.slots.iter().filter(|x| x.group == "military").count(), 2);
        assert_eq!(h.slots.iter().filter(|x| x.group == "hardpoint").count(), 9);
        assert_eq!(h.slots.iter().filter(|x| x.group == "utility").count(), 8);
        assert_eq!(s.hull("Type-10 Defender").map(|x| x.symbol.as_str()), Some("type9_military"));
    }

    #[test]
    fn what_fits_where() {
        let s = slots();
        let t10 = s.hull("type9_military").unwrap();
        let large = t10.slot("LargeHardpoint1").unwrap();
        assert!(s.fits(t10, large, "hpt_pulselaser_fixed_medium").is_ok(), "a medium weapon fits a large mount");
        assert!(s.fits(t10, large, "hpt_pulselaser_fixed_huge").is_err(), "a huge weapon does not");
        assert!(s.fits(t10, large, "hpt_shieldbooster_size0_class5").is_err(), "a utility module is not a weapon");
        let utility = t10.slot("TinyHardpoint1").unwrap();
        assert!(s.fits(t10, utility, "hpt_shieldbooster_size0_class5").is_ok());
        assert!(s.fits(t10, utility, "hpt_pulselaser_fixed_small").is_err());
        let military = t10.slot("Military01").unwrap();
        assert!(s.fits(t10, military, "int_hullreinforcement_size5_class2").is_ok());
        assert!(s.fits(t10, military, "int_hullreinforcement_size4_class2").is_ok(), "smaller is fine");
        assert!(s.fits(t10, military, "int_cargorack_size5_class1").is_err(), "no cargo in a military slot");
        let opt = t10.slot("Slot01_Size8").unwrap();
        assert!(s.fits(t10, opt, "int_cargorack_size8_class1").is_ok());
        assert!(s.fits(t10, opt, "int_fighterbay_size5_class1").is_ok(), "the Type-10 carries fighters");
        assert!(s.fits(t10, opt, "int_passengercabin_size5_class4").is_err(), "luxury cabins are for liners");
        let ls = t10.slot("LifeSupport").unwrap();
        assert!(s.fits(t10, ls, "int_lifesupport_size5_class5").is_ok());
        assert!(s.fits(t10, ls, "int_lifesupport_size4_class5").is_err(), "life support is exactly the slot's size");
        let fsd = t10.slot("FrameShiftDrive").unwrap();
        assert!(s.fits(t10, fsd, "int_hyperdrive_overcharge_size7_class5").is_ok());
        assert!(s.fits(t10, fsd, "int_hyperdrive_overcharge_size6_class5").is_err(), "an SCO drive is exactly the slot's size");
        assert!(s.fits(t10, fsd, "int_hyperdrive_size6_class5").is_ok(), "a plain drive may be smaller");
        // A slot that is not a slot.
        assert!(t10.slot("Slot09_Size2").is_none());
    }

    #[test]
    fn hull_bound_modules_stay_on_their_hulls() {
        let s = slots();
        let sidey = s.hull("sidewinder").unwrap();
        let opt = sidey.slots.iter().find(|x| x.group == "internal" && x.size >= 1 && x.slot != "PlanetaryApproachSuite").unwrap();
        assert!(s.fits(sidey, opt, "int_fighterbay_size5_class1").is_err(), "no hangar on a Sidewinder");
        let panther = s.hull("panthermkii").unwrap();
        let cargo = panther.slot("Cargo01").unwrap();
        assert!(s.fits(panther, cargo, "int_largecargorack_size8_class1").is_ok(), "the Mk II rack in the Panther's cargo slot");
        let plain = panther.slot("Slot01_Size8").unwrap();
        assert!(s.fits(panther, plain, "int_largecargorack_size8_class1").is_err(), "and nowhere else");
        assert!(s.fits(panther, plain, "int_cargorack_size8_class1").is_ok());
        let prospector = s.hull("lakonminer").unwrap();
        let mining = prospector.slot("LargeMiningHardpoint1").unwrap();
        assert!(s.fits(prospector, mining, "hpt_mininglaser_fixed_medium").is_ok());
        assert!(s.fits(prospector, mining, "hpt_pulselaser_fixed_medium").is_err(), "a mining hardpoint takes mining tools only");
    }

    /// The Armour slot offers the hull's own five bulkheads and nobody
    /// else's (maintainer, 2026-09-20: "we seem to be missing the various
    /// bulkheads").
    #[test]
    fn the_armour_slot_offers_the_hulls_five_bulkheads() {
        let s = slots();
        let t10 = s.hull("type9_military").unwrap();
        let armour = t10.slot("Armour").unwrap();
        let c = s.candidates(t10, armour);
        let items: Vec<&str> = c.iter().map(|(i, _)| *i).collect();
        assert_eq!(c.len(), 5, "{items:?}");
        assert!(items.contains(&"type9_military_armour_grade1"));
        assert!(items.contains(&"type9_military_armour_reactive"));
        assert!(c.iter().all(|(i, _)| i.starts_with("type9_military_armour_")), "{items:?}");
        assert!(s.fits(t10, armour, "sidewinder_armour_grade1").is_err(), "another hull's plating");
        assert!(s.fits(t10, armour, "int_hullreinforcement_size1_class1").is_err(), "a reinforcement package is not a bulkhead");
        assert_eq!(c.iter().find(|(i, _)| *i == "type9_military_armour_grade3").map(|(_, k)| k.name.as_str()), Some("Military Grade Composite"));
        for h in s.hulls() {
            let n = s.candidates(h, h.slot("Armour").unwrap()).len();
            assert!(n >= 5, "{}: {n} bulkheads", h.name);
        }
    }

    #[test]
    fn candidates_are_sorted_and_only_what_fits() {
        let s = slots();
        let t10 = s.hull("type9_military").unwrap();
        let c = s.candidates(t10, t10.slot("Military01").unwrap());
        assert!(!c.is_empty());
        assert!(c.iter().all(|(_, k)| ["ihrp", "isrp", "imahrp", "imrp", "iscb"].contains(&k.kind.as_str())));
        assert!(c.iter().all(|(_, k)| k.class <= 5));
        let names: Vec<&str> = c.iter().map(|(_, k)| k.name.as_str()).collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted, "by kind name");
    }

    #[test]
    fn a_ship_carries_one_shield_generator() {
        let s = slots();
        let notes = s.over_limit(&[
            ("Slot01_Size8".into(), "int_shieldgenerator_size8_class5".into()),
            ("Slot02_Size7".into(), "int_shieldgenerator_size7_class5".into()),
            ("Slot03_Size6".into(), "int_cargorack_size6_class1".into()),
        ]);
        assert_eq!(notes.len(), 1, "{notes:?}");
        assert!(notes[0].contains("shield generator"), "{notes:?}");
        assert!(s.over_limit(&[("Slot01_Size8".into(), "int_shieldgenerator_size8_class5".into())]).is_empty());
    }

    #[test]
    fn the_stock_hull_is_a_loadout() {
        let s = slots();
        let t10 = s.hull("type9_military").unwrap();
        let v = s.stock_loadout(t10);
        assert_eq!(v["Ship"], "type9_military");
        assert_eq!(v["Ship_Localised"], "Type-10 Defender");
        let mods = v["Modules"].as_array().unwrap();
        let fsd = mods.iter().find(|m| m["Slot"] == "FrameShiftDrive").expect("a drive");
        assert_eq!(fsd["Item"], "int_hyperdrive_size6_class1", "stock 6E drive (class 1 is E)");
        assert_eq!(v["FuelCapacity"]["Main"], 64.0, "stock 6C tank");
        assert!(mods.iter().any(|m| m["Slot"] == "Armour"));
        assert!(mods.iter().any(|m| m["Slot"] == "ShipCockpit"));
        // Every hull has a stock core.
        for h in s.hulls() {
            let v = s.stock_loadout(h);
            let mods = v["Modules"].as_array().unwrap();
            for core in ["PowerPlant", "MainEngines", "FrameShiftDrive", "LifeSupport", "PowerDistributor", "Radar", "FuelTank"] {
                assert!(mods.iter().any(|m| m["Slot"] == core), "{}: stock {core}", h.name);
            }
        }
        assert_eq!(s.hulls().len(), 48);
    }
}
