//! Commodity display metadata, generated from the community-maintained
//! FDevIDs tables (github.com/EDCD/FDevIDs: commodity.csv and
//! rare_commodity.csv), Copyright the EDCD/FDevIDs contributors. The
//! repository carries no license file; the data is Frontier's factual ID
//! assignments as collected by the community. Regenerate by re-running
//! the generator against the current CSVs when Frontier adds commodities
//! (the columns are id,symbol,category,name — category before name).
//!
//! `(symbol, display name, category)`, sorted by symbol. Symbols are
//! stored in the ingest's canonical form — lowercase — so the upsert
//! lands on the rows market data references (see 83b65e5 for the
//! CamelCase orphan-row bug this prevents).

pub const COMMODITY_METADATA: &[(&str, &str, &str)] = &[
    ("advancedcatalysers", "Advanced Catalysers", "Technology"),
    ("advancedmedicines", "Advanced Medicines", "Medicines"),
    (
        "advert1",
        "Ultra-Compact Processor Prototypes",
        "Consumer Items",
    ),
    ("aerialedenapple", "Eden Apples of Aerial", "Foods"),
    ("aganipperush", "Aganippe Rush", "Medicines"),
    ("agriculturalmedicines", "Agri-Medicines", "Medicines"),
    ("agronomictreatment", "Agronomic Treatment", "Chemicals"),
    ("airelics", "AI Relics", "Salvage"),
    ("alacarakmoskinart", "Alacarakmo Skin Art", "Consumer Items"),
    (
        "albinoquechuamammoth",
        "Albino Quechua Mammoth Meat",
        "Foods",
    ),
    ("alexandrite", "Alexandrite", "Minerals"),
    ("algae", "Algae", "Foods"),
    ("alieneggs", "Leathery Eggs", "Consumer Items"),
    ("altairianskin", "Altairian Skin", "Consumer Items"),
    ("aluminium", "Aluminium", "Metals"),
    ("alyabodilysoap", "Alya Body Soap", "Medicines"),
    ("ancientcasket", "Guardian Casket", "Salvage"),
    ("ancientkey", "Ancient Key", "Salvage"),
    ("ancientorb", "Guardian Orb", "Salvage"),
    ("ancientrelic", "Guardian Relic", "Salvage"),
    ("ancientrelictg", "Unclassified Relic", "Salvage"),
    ("ancienttablet", "Guardian Tablet", "Salvage"),
    ("ancienttotem", "Guardian Totem", "Salvage"),
    ("ancienturn", "Guardian Urn", "Salvage"),
    ("anduligafireworks", "Anduliga Fire Works", "Consumer Items"),
    ("animaleffigies", "Crom Silver Fesh", "Legal Drugs"),
    ("animalmeat", "Animal Meat", "Foods"),
    ("animalmonitors", "Animal Monitors", "Technology"),
    (
        "antimattercontainmentunit",
        "Antimatter Containment Unit",
        "Salvage",
    ),
    ("antiquejewellery", "Antique Jewellery", "Salvage"),
    ("antiquities", "Antiquities", "Salvage"),
    ("anynacoffee", "Any Na Coffee", "Foods"),
    ("apavietii", "Apa Vietii", "Legal Drugs"),
    ("aquaponicsystems", "Aquaponic Systems", "Technology"),
    (
        "aroucaconventualsweets",
        "Arouca Conventual Sweets",
        "Foods",
    ),
    ("articulationmotors", "Articulation Motors", "Machinery"),
    ("assaultplans", "Assault Plans", "Salvage"),
    (
        "atmosphericextractors",
        "Atmospheric Processors",
        "Machinery",
    ),
    ("autofabricators", "Auto-Fabricators", "Technology"),
    ("azcancriformula42", "AZ Cancri Formula 42", "Technology"),
    ("bakedgreebles", "Baked Greebles", "Foods"),
    ("baltahsinevacuumkrill", "Baltah'sine Vacuum Krill", "Foods"),
    (
        "bankiamphibiousleather",
        "Banki Amphibious Leather",
        "Textiles",
    ),
    ("basicmedicines", "Basic Medicines", "Medicines"),
    ("basicnarcotics", "Narcotics", "Legal Drugs"),
    ("bastnasite", "Bastnasite", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("bastsnakegin", "Bast Snake Gin", "Legal Drugs"),
    ("battleweapons", "Battle Weapons", "Weapons"),
    ("bauxite", "Bauxite", "Minerals"),
    ("beer", "Beer", "Legal Drugs"),
    ("belalansrayleather", "Belalans Ray Leather", "Textiles"),
    ("benitoite", "Benitoite", "Minerals"),
    ("bertrandite", "Bertrandite", "Minerals"),
    ("beryllium", "Beryllium", "Metals"),
    ("bioreducinglichen", "Bioreducing Lichen", "Technology"),
    ("biowaste", "Biowaste", "Waste"),
    ("bismuth", "Bismuth", "Metals"),
    ("bluemilk", "Azure Milk", "Foods"),
    ("bootlegliquor", "Bootleg Liquor", "Legal Drugs"),
    (
        "borasetanipathogenetics",
        "Borasetani Pathogenetics",
        "Weapons",
    ),
    ("bromellite", "Bromellite", "Minerals"),
    ("buckyballbeermats", "Buckyball Beer Mats", "Consumer Items"),
    ("buildingfabricators", "Building Fabricators", "Machinery"),
    (
        "burnhambiledistillate",
        "Burnham Bile Distillate",
        "Legal Drugs",
    ),
    ("cd75catcoffee", "CD-75 Kitten Brand Coffee", "Foods"),
    ("centaurimegagin", "Centauri Mega Gin", "Legal Drugs"),
    (
        "ceramiccomposites",
        "Ceramic Composites",
        "Industrial Materials",
    ),
    ("ceremonialheiketea", "Ceremonial Heike Tea", "Foods"),
    ("cetiaepyornisegg", "Aepyornis Egg", "Foods"),
    ("cetirabbits", "Ceti Rabbits", "Foods"),
    ("chameleoncloth", "Chameleon Cloth", "Textiles"),
    ("chateaudeaegaeon", "Chateau De Aegaeon", "Legal Drugs"),
    ("chemicalwaste", "Chemical Waste", "Waste"),
    (
        "cherbonesbloodcrystals",
        "Cherbones Blood Crystals",
        "Metals",
    ),
    ("chieridanimarinepaste", "Chi Eridani Marine Paste", "Foods"),
    (
        "classifiedexperimentalequipment",
        "Classified Experimental Equipment",
        "Technology",
    ),
    ("clothing", "Clothing", "Consumer Items"),
    ("cmmcomposite", "CMM Composite", "Industrial Materials"),
    ("cobalt", "Cobalt", "Metals"),
    ("coffee", "Coffee", "Foods"),
    ("coltan", "Coltan", "Minerals"),
    ("combatstabilisers", "Combat Stabilisers", "Medicines"),
    ("comercialsamples", "Commercial Samples", "Salvage"),
    ("computercomponents", "Computer Components", "Technology"),
    ("conductivefabrics", "Conductive Fabrics", "Textiles"),
    (
        "consumertechnology",
        "Consumer Technology",
        "Consumer Items",
    ),
    (
        "coolinghoses",
        "Micro-weave Cooling Hoses",
        "Industrial Materials",
    ),
    ("copper", "Copper", "Metals"),
    (
        "coquimspongiformvictuals",
        "Coquim Spongiform Victuals",
        "Foods",
    ),
    ("coralsap", "Coral Sap", "Salvage"),
    ("cropharvesters", "Crop Harvesters", "Machinery"),
    ("cryolite", "Cryolite", "Minerals"),
    ("crystallinespheres", "Crystalline Spheres", "Salvage"),
    (
        "curatedcommodity",
        "Curated Commodity Package",
        "Industrial Materials",
    ),
    ("damagedescapepod", "Damaged Escape Pod", "Salvage"),
    ("damnacarapaces", "Damna Carapaces", "Textiles"),
    ("datacore", "Data Core", "Salvage"),
    ("deltaphoenicispalms", "Delta Phoenicis Palms", "Chemicals"),
    ("deuringastruffles", "Deuringas Truffles", "Foods"),
    ("deuterium", "Deuterium", "Chemicals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    (
        "diagnosticsensor",
        "Hardware Diagnostic Sensor",
        "Technology",
    ),
    ("diamond", "Diamond", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("diplomaticbag", "Diplomatic Bag", "Salvage"),
    ("disomacorn", "Diso Ma Corn", "Foods"),
    (
        "domesticappliances",
        "Domestic Appliances",
        "Consumer Items",
    ),
    ("drones", "Limpets", "NonMarketable"),
    ("duradrives", "Duradrives", "Consumer Items"),
    ("earthrelics", "Earth Relics", "Salvage"),
    ("eleuthermals", "Eleu Thermals", "Consumer Items"),
    ("emergencypowercells", "Emergency Power Cells", "Machinery"),
    ("encripteddatastorage", "Encrypted Data Storage", "Salvage"),
    (
        "encryptedcorrespondence",
        "Encrypted Correspondence",
        "Salvage",
    ),
    ("eraninpearlwhisky", "Eranin Pearl Whisky", "Legal Drugs"),
    ("eshuumbrellas", "Eshu Umbrellas", "Consumer Items"),
    ("esusekucaviar", "Esuseku Caviar", "Foods"),
    ("ethgrezeteabuds", "Ethgreze Tea Buds", "Foods"),
    ("evacuationshelter", "Evacuation Shelter", "Consumer Items"),
    ("exhaustmanifold", "Exhaust Manifold", "Machinery"),
    ("explosives", "Explosives", "Chemicals"),
    ("fish", "Fish", "Foods"),
    ("foodcartridges", "Food Cartridges", "Foods"),
    ("fossilremnants", "Fossil Remnants", "Salvage"),
    ("fruitandvegetables", "Fruit and Vegetables", "Foods"),
    ("fujintea", "Fujin Tea", "Foods"),
    ("galactictravelguide", "Galactic Travel Guide", "Salvage"),
    ("gallite", "Gallite", "Minerals"),
    ("gallium", "Gallium", "Metals"),
    ("geawendancedust", "Geawen Dance Dust", "Legal Drugs"),
    ("genebank", "Gene Bank", "Salvage"),
    ("geologicalequipment", "Geological Equipment", "Machinery"),
    ("geologicalsamples", "Geological Samples", "Salvage"),
    ("gerasiangueuzebeer", "Gerasian Gueuze Beer", "Legal Drugs"),
    ("giantirukamasnails", "Giant Irukama Snails", "Foods"),
    ("giantverrix", "Giant Verrix", "Machinery"),
    (
        "gilyasignatureweapons",
        "Gilya Signature Weapons",
        "Weapons",
    ),
    ("gold", "Gold", "Metals"),
    ("gomanyauponcoffee", "Goman Yaupon Coffee", "Foods"),
    ("goslarite", "Goslarite", "Minerals"),
    ("grain", "Grain", "Foods"),
    ("grandidierite", "Grandidierite", "Minerals"),
    ("haematite", "Haematite", "Minerals"),
    ("hafnium178", "Hafnium 178", "Metals"),
    ("haidneblackbrew", "Haiden Black Brew", "Foods"),
    ("harmasilversearum", "Harma Silver Sea Rum", "Legal Drugs"),
    (
        "havasupaidreamcatcher",
        "Havasupai Dream Catcher",
        "Consumer Items",
    ),
    ("hazardousenvironmentsuits", "H.E. Suits", "Technology"),
    ("heatsinkinterlink", "Heatsink Interlink", "Machinery"),
    ("heliostaticfurnaces", "Microbial Furnaces", "Machinery"),
    ("helium", "Helium", "Chemicals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("helium3", "Helium-3", "Chemicals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("helvetitjpearls", "Helvetitj Pearls", "Metals"),
    ("hip10175bushmeat", "HIP 10175 Bush Meat", "Foods"),
    ("hip118311swarm", "HIP 118311 Swarm", "Weapons"),
    ("hip41181squid", "HIP Proto-Squid", "Foods"),
    ("hiporganophosphates", "HIP Organophosphates", "Chemicals"),
    ("hnshockmount", "HN Shock Mount", "Machinery"),
    ("holvaduellingblades", "Holva Duelling Blades", "Weapons"),
    ("honestypills", "Honesty Pills", "Medicines"),
    ("hostage", "Hostages", "Salvage"),
    ("hr7221wheat", "HR 7221 Wheat", "Foods"),
    ("hydrogenfuel", "Hydrogen Fuel", "Chemicals"),
    ("hydrogenperoxide", "Hydrogen Peroxide", "Chemicals"),
    ("imperialslaves", "Imperial Slaves", "Slavery"),
    ("indibourbon", "Indi Bourbon", "Legal Drugs"),
    ("indite", "Indite", "Minerals"),
    ("indium", "Indium", "Metals"),
    (
        "insulatingmembrane",
        "Insulating Membrane",
        "Industrial Materials",
    ),
    ("iondistributor", "Ion Distributor", "Machinery"),
    ("iridium", "Iridium", "Metals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("jadeite", "Jadeite", "Minerals"),
    (
        "jaquesquinentianstill",
        "Jaques Quinentian Still",
        "Consumer Items",
    ),
    (
        "jaradharrepuzzlebox",
        "Jaradharre Puzzle Box",
        "Consumer Items",
    ),
    ("jarouarice", "Jaroua Rice", "Foods"),
    ("jotunmookah", "Jotun Mookah", "Textiles"),
    (
        "kachiriginleaches",
        "Kachirigin Filter Leeches",
        "Medicines",
    ),
    ("kamitracigars", "Kamitra Cigars", "Legal Drugs"),
    (
        "kamorinhistoricweapons",
        "Kamorin Historic Weapons",
        "Weapons",
    ),
    ("karetiicouture", "Karetii Couture", "Consumer Items"),
    ("karsukilocusts", "Karsuki Locusts", "Foods"),
    ("kinagoinstruments", "Kinago Violins", "Consumer Items"),
    ("konggaale", "Kongga Ale", "Legal Drugs"),
    ("korrokungpellets", "Koro Kung Pellets", "Chemicals"),
    ("landmines", "Landmines", "Weapons"),
    ("lanthanum", "Lanthanum", "Metals"),
    (
        "largeexplorationdatacash",
        "Large Survey Data Cache",
        "Salvage",
    ),
    ("lavianbrandy", "Lavian Brandy", "Legal Drugs"),
    ("leather", "Leather", "Textiles"),
    ("leestianeviljuice", "Leestian Evil Juice", "Legal Drugs"),
    ("lepidolite", "Lepidolite", "Minerals"),
    ("lftvoidextractcoffee", "Void Extract Coffee", "Foods"),
    ("liquidoxygen", "Liquid oxygen", "Chemicals"),
    ("liquor", "Liquor", "Legal Drugs"),
    ("lithium", "Lithium", "Metals"),
    ("lithiumhydroxide", "Lithium Hydroxide", "Minerals"),
    ("livehecateseaworms", "Live Hecate Sea Worms", "Foods"),
    (
        "lowtemperaturediamond",
        "Low Temperature Diamonds",
        "Minerals",
    ),
    ("ltthypersweet", "LTT Hyper Sweet", "Foods"),
    ("lyraeweed", "Lyrae Weed", "Legal Drugs"),
    ("m3_tissuesample_membrane", "Mollusc Membrane", "Salvage"),
    ("m3_tissuesample_mycelium", "Mollusc Mycelium", "Salvage"),
    ("m3_tissuesample_spores", "Mollusc Spores", "Salvage"),
    ("m_tissuesample_fluid", "Mollusc Fluid", "Salvage"),
    ("m_tissuesample_nerves", "Mollusc Brain Tissue", "Salvage"),
    ("m_tissuesample_soft", "Mollusc Soft Tissue", "Salvage"),
    ("magnesite", "Magnesite", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("magneticemittercoil", "Magnetic Emitter Coil", "Machinery"),
    ("marinesupplies", "Marine Equipment", "Machinery"),
    ("masterchefs", "Master Chefs", "Slavery"),
    ("mechucoshightea", "Mechucos High Tea", "Foods"),
    ("medbstarlube", "Medb Starlube", "Chemicals"),
    (
        "medicaldiagnosticequipment",
        "Medical Diagnostic Equipment",
        "Technology",
    ),
    ("metaalloys", "Meta-Alloys", "Industrial Materials"),
    ("methaneclathrate", "Methane Clathrate", "Minerals"),
    (
        "methanolmonohydratecrystals",
        "Methanol Monohydrate Crystals",
        "Minerals",
    ),
    ("microcontrollers", "Micro Controllers", "Technology"),
    ("militarygradefabrics", "Military Grade Fabrics", "Textiles"),
    ("militaryintelligence", "Military Intelligence", "Salvage"),
    ("mineralextractors", "Mineral Extractors", "Machinery"),
    ("mineraloil", "Mineral Oil", "Chemicals"),
    ("modularterminals", "Modular Terminals", "Machinery"),
    ("moissanite", "Moissanite", "Minerals"),
    ("mokojingbeastfeast", "Mokojing Beast Feast", "Foods"),
    ("momusbogspaniel", "Momus Bog Spaniel", "Consumer Items"),
    ("monazite", "Monazite", "Minerals"),
    (
        "motronaexperiencejelly",
        "Motrona Experience Jelly",
        "Legal Drugs",
    ),
    ("mukusubiichitinos", "Mukusubii Chitin-os", "Foods"),
    ("mulachigiantfungus", "Mulachi Giant Fungus", "Foods"),
    ("musgravite", "Musgravite", "Minerals"),
    ("mutomimager", "Muon Imager", "Technology"),
    ("mysteriousidol", "Mysterious Idol", "Salvage"),
    ("nanobreakers", "Nanobreakers", "Technology"),
    ("nanomedicines", "Nanomedicines", "Medicines"),
    ("naturalfabrics", "Natural Fabrics", "Textiles"),
    (
        "neofabricinsulation",
        "Neofabric Insulation",
        "Industrial Materials",
    ),
    ("neritusberries", "Neritus Berries", "Foods"),
    ("nerveagents", "Nerve Agents", "Chemicals"),
    ("ngadandarifireopals", "Ngadandari Fire Opals", "Metals"),
    (
        "ngunamodernantiques",
        "Nguna Modern Antiques",
        "Consumer Items",
    ),
    ("njangarisaddles", "Njangari Saddles", "Consumer Items"),
    (
        "noneuclidianexotanks",
        "Non Euclidian Exotanks",
        "Machinery",
    ),
    ("nonlethalweapons", "Non-Lethal Weapons", "Weapons"),
    ("occupiedcryopod", "Occupied Escape Pod", "Salvage"),
    ("ochoengchillies", "Ochoeng Chillies", "Foods"),
    ("olivine", "Olivine", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("onionhead", "Onionhead", "Legal Drugs"),
    ("onionheada", "Onionhead Alpha Strain", "Legal Drugs"),
    ("onionheadb", "Onionhead Beta Strain", "Legal Drugs"),
    ("onionheadc", "Onionhead Gamma Strain", "Legal Drugs"),
    ("opal", "Void Opal", "Minerals"),
    (
        "ophiuchiexinoartefacts",
        "Ophiuch Exino Artefacts",
        "Consumer Items",
    ),
    ("orrerianviciousbrew", "Orrerian Vicious Brew", "Foods"),
    ("osmium", "Osmium", "Metals"),
    ("p_particulatesample", "Anomaly Particles", "Salvage"),
    ("painite", "Painite", "Minerals"),
    ("palladium", "Palladium", "Metals"),
    ("pantaaprayersticks", "Pantaa Prayer Sticks", "Medicines"),
    ("pavoniseargrubs", "Pavonis Ear Grubs", "Legal Drugs"),
    ("performanceenhancers", "Performance Enhancers", "Medicines"),
    ("periclasedunite", "Periclase Dunite", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("personaleffects", "Personal Effects", "Salvage"),
    ("personalgifts", "Festive Gifts", "Salvage"),
    ("personalweapons", "Personal Weapons", "Weapons"),
    ("pesticides", "Pesticides", "Chemicals"),
    ("platinum", "Platinum", "Metals"),
    ("platinumaloy", "Platinum Alloy", "Metals"),
    ("politicalprisoner", "Political Prisoners", "Salvage"),
    ("polymers", "Polymers", "Industrial Materials"),
    ("powerconverter", "Power Converter", "Machinery"),
    ("powergenerators", "Power Generators", "Machinery"),
    ("powergridassembly", "Energy Grid Assembly", "Machinery"),
    ("powertransferconduits", "Power Transfer Bus", "Machinery"),
    ("praseodymium", "Praseodymium", "Metals"),
    ("preciousgems", "Precious Gems", "Salvage"),
    ("progenitorcells", "Progenitor Cells", "Medicines"),
    (
        "prohibitedresearchmaterials",
        "Prohibited Research Materials",
        "Salvage",
    ),
    ("pyrophyllite", "Pyrophyllite", "Minerals"),
    ("quartzpyroxenite", "Quartz Pyroxenite", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("radiationbaffle", "Radiation Baffle", "Machinery"),
    ("rajukrustoves", "Rajukru Multi-Stoves", "Consumer Items"),
    ("rapabaosnakeskins", "Rapa Bao Snake Skins", "Textiles"),
    ("reactivearmour", "Reactive Armour", "Weapons"),
    (
        "reinforcedmountingplate",
        "Reinforced Mounting Plate",
        "Machinery",
    ),
    (
        "resonatingseparators",
        "Resonating Separators",
        "Technology",
    ),
    ("rhodplumsite", "Rhodplumsite", "Minerals"),
    ("robotics", "Robotics", "Technology"),
    ("rockforthfertiliser", "Rockforth Fertiliser", "Chemicals"),
    ("ruby", "Ruby", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("rusanioldsmokey", "Rusani Old Smokey", "Legal Drugs"),
    ("rutile", "Rutile", "Minerals"),
    ("s6_tissuesample_cells", "Pod Outer Tissue", "Salvage"),
    ("s6_tissuesample_coenosarc", "Pod Shell Tissue", "Salvage"),
    ("s6_tissuesample_mesoglea", "Pod Mesoglea", "Salvage"),
    ("s9_tissuesample_shell", "Pod Tissue", "Salvage"),
    ("s_tissuesample_cells", "Pod Core Tissue", "Salvage"),
    ("s_tissuesample_core", "Pod Surface Tissue", "Salvage"),
    ("s_tissuesample_surface", "Pod Dead Tissue", "Salvage"),
    ("samarium", "Samarium", "Metals"),
    ("sanumameat", "Sanuma Decorative Meat", "Foods"),
    ("sap8corecontainer", "SAP 8 Core Container", "Salvage"),
    ("sapphire", "Sapphire", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("saxonwine", "Saxon Wine", "Legal Drugs"),
    ("scientificresearch", "Scientific Research", "Salvage"),
    ("scientificsamples", "Scientific Samples", "Salvage"),
    ("scrap", "Scrap", "Waste"),
    ("semiconductors", "Semiconductors", "Industrial Materials"),
    ("serendibite", "Serendibite", "Minerals"),
    (
        "shanscharisorchid",
        "Shan's Charis Orchid",
        "Consumer Items",
    ),
    ("silver", "Silver", "Metals"),
    ("skimercomponents", "Skimmer Components", "Machinery"),
    ("slaves", "Slaves", "Slavery"),
    (
        "smallexplorationdatacash",
        "Small Survey Data Cache",
        "Salvage",
    ),
    ("soontillrelics", "Soontill Relics", "Consumer Items"),
    ("sothiscrystallinegold", "Sothis Crystalline Gold", "Metals"),
    ("spacepioneerrelics", "Space Pioneer Relics", "Salvage"),
    ("steel", "Steel", "Metals"),
    (
        "structuralregulators",
        "Structural Regulators",
        "Technology",
    ),
    ("superconductors", "Superconductors", "Industrial Materials"),
    ("surfacestabilisers", "Surface Stabilisers", "Chemicals"),
    ("survivalequipment", "Survival Equipment", "Consumer Items"),
    ("syntheticfabrics", "Synthetic Fabrics", "Textiles"),
    ("syntheticmeat", "Synthetic Meat", "Foods"),
    ("syntheticreagents", "Synthetic Reagents", "Chemicals"),
    ("taaffeite", "Taaffeite", "Minerals"),
    ("tacticaldata", "Tactical Data", "Salvage"),
    ("tanmarktranquiltea", "Tanmark Tranquil Tea", "Foods"),
    ("tantalum", "Tantalum", "Metals"),
    ("tarachtorspice", "Tarach Spice", "Legal Drugs"),
    ("taurichimes", "Tauri Chimes", "Consumer Items"),
    ("tea", "Tea", "Foods"),
    ("telemetrysuite", "Telemetry Suite", "Technology"),
    (
        "terrainenrichmentsystems",
        "Land Enrichment Systems",
        "Technology",
    ),
    (
        "terramaterbloodbores",
        "Terra Mater Blood Bores",
        "Medicines",
    ),
    ("thallium", "Thallium", "Metals"),
    ("thargoidbonefragments", "Bone Fragments", "Salvage"),
    ("thargoidcystspecimen", "Cyst Specimen", "Salvage"),
    (
        "thargoidgeneratortissuesample",
        "Caustic Tissue Sample",
        "Salvage",
    ),
    ("thargoidheart", "Thargoid Heart", "Salvage"),
    ("thargoidorgansample", "Organ Sample", "Salvage"),
    ("thargoidpod", "Xenobiological Prison Pod", "Salvage"),
    (
        "thargoidscouttissuesample",
        "Thargoid Scout Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype1",
        "Thargoid Cyclops Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype10a",
        "Titan Maw Deep Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype10b",
        "Titan Maw Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype10c",
        "Titan Maw Partial Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype2",
        "Thargoid Basilisk Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype3",
        "Thargoid Medusa Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype4",
        "Thargoid Hydra Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype5",
        "Thargoid Orthrus Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype6",
        "Thargoid Glaive Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype7",
        "Thargoid Scythe Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype9a",
        "Titan Deep Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype9b",
        "Titan Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtissuesampletype9c",
        "Titan Partial Tissue Sample",
        "Salvage",
    ),
    (
        "thargoidtitandrivecomponent",
        "Titan Drive Component",
        "Salvage",
    ),
    ("thehuttonmug", "The Hutton Mug", "Consumer Items"),
    ("thermalcoolingunits", "Thermal Cooling Units", "Machinery"),
    ("thorium", "Thorium", "Metals"),
    ("thortveitite", "Thortveitite", "Minerals"), // 4.4.1.0, confirmed by EDCD FDevIDs 2026-09-06
    ("thrutiscream", "Thrutis Cream", "Legal Drugs"),
    ("tiegfriessynthsilk", "Tiegfries Synth Silk", "Textiles"),
    ("timecapsule", "Time Capsule", "Salvage"),
    (
        "tiolcewaste2pasteunits",
        "Tiolce Waste2Paste Units",
        "Consumer Items",
    ),
    ("titanium", "Titanium", "Metals"),
    ("tobacco", "Tobacco", "Legal Drugs"),
    ("toxandjivirocide", "Toxandji Virocide", "Chemicals"),
    ("toxicwaste", "Toxic Waste", "Waste"),
    ("transgeniconionhead", "Lucan Onionhead", "Legal Drugs"),
    (
        "trinketsoffortune",
        "Trinkets of Hidden Fortune",
        "Consumer Items",
    ),
    ("tritium", "Tritium", "Chemicals"),
    ("unknownartifact", "Thargoid Sensor", "Salvage"),
    ("unknownartifact2", "Thargoid Probe", "Salvage"),
    ("unknownartifact3", "Thargoid Link", "Salvage"),
    (
        "unknownbiologicalmatter",
        "Thargoid Biological Matter",
        "Salvage",
    ),
    ("unknownmineral", "Impure Spire Mineral", "Salvage"),
    (
        "unknownrefinedmineral",
        "Semi-Refined Spire Mineral",
        "Salvage",
    ),
    ("unknownresin", "Thargoid Resin", "Salvage"),
    ("unknownsack", "Protective Membrane Scrap", "Salvage"),
    (
        "unknowntechnologysamples",
        "Thargoid Technology Samples",
        "Salvage",
    ),
    ("unocuppiedescapepod", "Unoccupied Escape Pod", "Salvage"),
    ("unstabledatacore", "Unstable Data Core", "Salvage"),
    ("uraninite", "Uraninite", "Minerals"),
    ("uranium", "Uranium", "Metals"),
    ("usscargoancientartefact", "Ancient Artefact", "Salvage"),
    ("usscargoblackbox", "Black Box", "Salvage"),
    (
        "usscargoexperimentalchemicals",
        "Experimental Chemicals",
        "Salvage",
    ),
    ("usscargomilitaryplans", "Military Plans", "Salvage"),
    ("usscargoprototypetech", "Prototype Tech", "Salvage"),
    ("usscargorareartwork", "Rare Artwork", "Salvage"),
    (
        "usscargorebeltransmissions",
        "Rebel Transmissions",
        "Salvage",
    ),
    (
        "usscargotechnicalblueprints",
        "Technical Blueprints",
        "Salvage",
    ),
    ("usscargotradedata", "Trade Data", "Salvage"),
    ("uszaiantreegrub", "Uszaian Tree Grub", "Foods"),
    ("utgaroarmillenialeggs", "Utgaroar Millennial Eggs", "Foods"),
    ("uzumokulowgwings", "Uzumoku Low-G Wings", "Consumer Items"),
    (
        "vanayequirhinofur",
        "Vanayequi Ceratomorpha Fur",
        "Textiles",
    ),
    ("vegaslimweed", "Vega Slimweed", "Medicines"),
    ("vherculisbodyrub", "V Herculis Body Rub", "Medicines"),
    ("vidavantianlace", "Vidavantian Lace", "Consumer Items"),
    ("volkhabbeedrones", "Volkhab Bee Drones", "Machinery"),
    ("water", "Water", "Chemicals"),
    ("waterpurifiers", "Water Purifiers", "Machinery"),
    ("watersofshintara", "The Waters of Shintara", "Medicines"),
    ("wheemetewheatcakes", "Wheemete Wheat Cakes", "Foods"),
    ("wine", "Wine", "Legal Drugs"),
    ("witchhaulkobebeef", "Witchhaul Kobe Beef", "Foods"),
    ("wolf1301fesh", "Wolf Fesh", "Legal Drugs"),
    ("wreckagecomponents", "Wreckage Components", "Salvage"),
    (
        "wulpahyperboresystems",
        "Wulpa Hyperbore Systems",
        "Machinery",
    ),
    ("wuthielokufroth", "Wuthielo Ku Froth", "Legal Drugs"),
    ("xihecompanions", "Xihe Biomorphic Companions", "Technology"),
    ("yasokondileaf", "Yaso Kondi Leaf", "Legal Drugs"),
    ("zeesszeantglue", "Zeessze Ant Grub Glue", "Consumer Items"),
];
