// Something to read while a route plots. The two phases that mean
// something to a person (reading a Spansh plot, building the neutron index
// the first time) say so; the rest is the trip being planned, mundanely,
// in the voice of the selected persona.
export const LINES = {
  standard: {
    import: ["Reading the Spansh plot…"],
    neutrons: ["Indexing neutron stars for the highway (first time only)…"],
    plot: [
      "Planning potty breaks…",
      "Planning food stops…",
      "Sightseeing…",
      "Avoiding construction…",
      "Asking for directions…",
      "Packing snacks…",
      "Arguing with the satnav…",
      "Checking the tyre pressure…",
      "Counting the stars. All of them…",
      "Reading the map upside down…",
      "Folding the map back up…",
      "Finding the toll-free route…",
      "Looking for a nice view…",
      "Waiting for the kettle…",
      "Adjusting the mirrors…",
      "Checking nobody's sitting in the good seat…",
      "Untangling the headphone cable…",
      "Picking a playlist for the long bit…",
      "Making sure we packed the towel…",
      "Rehearsing the arrival announcement…",
    ],
  },
  butler: {
    neutrons: ["Cataloguing the neutron stars, Commander. A one-time formality."],
    plot: [
      "Arranging the itinerary…",
      "Pencilling in the refreshment stops…",
      "Consulting the charts…",
      "Selecting only the most respectable neutron stars…",
      "Seeing to the fuel arrangements…",
      "Avoiding the rougher neighbourhoods…",
      "Pressing the route before wearing it…",
      "Discreetly shortening the journey…",
      "Laying out the jumps in order of appearance…",
      "Enquiring after the scenic option, then declining it…",
      "Ensuring the tank is never embarrassed…",
      "Attending to the finer details of the last few jumps…",
      "Polishing the plan…",
      "Choosing stops where one might stretch one's legs…",
      "A moment, Commander. Excellence takes a little longer…",
      "Confirming the highway is open at this hour…",
      "Setting aside a reserve, as one does…",
      "Comparing routes so you need not…",
      "Straightening the line between here and there…",
      "The route will be ready presently…",
    ],
  },
  sassy: {
    neutrons: ["Cataloguing neutron stars. Yes, all of them. Sit tight."],
    plot: [
      "Planning rest stops. And potty breaks.",
      "Finding you a road, Commander. Patience is a virtue.",
      "Charting. Try not to touch anything.",
      "Avoiding construction. And your opinions.",
      "Sightseeing. You'll like it, I promise.",
      "Counting jumps so you don't have to.",
      "Doing the maths you'd get wrong.",
      "Picking neutron stars that won't cook the drive. Much.",
      "Packing snacks. Not for you.",
      "Finding the scenic route, then ignoring it.",
      "Weighing the fuel against your optimism.",
      "Reading the map. Right way up, unlike some people.",
      "Choosing stops with somewhere to land. You're welcome.",
      "Skipping the parts of the galaxy nobody visits for a reason.",
      "Making the long way look short. That's the job.",
      "Charting a course. Hands off the throttle.",
      "Reconsidering the whole trip. Twice.",
      "Plotting. This is the quiet part. Enjoy it.",
      "Working out which stars are lying about their fuel.",
      "Nearly there. Which is what I say about the route, too.",
    ],
  },
  robotic: {
    neutrons: ["NEUTRON INDEX: BUILDING."],
    plot: [
      "REST STOPS: SCHEDULING.",
      "SNACKS: ALLOCATED.",
      "CONSTRUCTION: AVOIDING.",
      "ROUTE: OPTIMISING.",
      "SCENERY: RATED.",
      "FUEL: BUDGETED.",
      "NEUTRON CONES: SELECTED.",
      "HIGHWAY: JOINING.",
      "DETOURS: DECLINED.",
      "CANDIDATES: COMPARING.",
      "JUMP COUNT: MINIMISING.",
      "TANK: SIMULATED.",
      "MARGINS: APPLIED.",
      "STAR CATALOGUE: CONSULTED.",
      "SHORTCUT: EVALUATED. REJECTED.",
      "PATIENCE: RECOMMENDED.",
      "WAYPOINTS: ORDERED.",
      "ARRIVAL: PREDICTED.",
      "COFFEE: NOT AVAILABLE.",
      "PLOT: CONVERGING.",
    ],
  },
  sultry: {
    neutrons: ["Let me find every bright star between us and there…"],
    plot: [
      "Planning our little stops…",
      "Packing something sweet for the road…",
      "Finding you a view worth the wait…",
      "Charting the fast way for you, Commander…",
      "Choosing the stars we'll pass under…",
      "Making the long way feel short…",
      "Lining up the neutrons like candles…",
      "Saving the best view for the last jump…",
      "Counting the jumps. I'll stay for every one…",
      "Reading the map by starlight…",
      "Picking out the quiet stretches…",
      "Keeping a little fuel in reserve, for us…",
      "Drawing the line from here to there. Slowly…",
      "The good routes take a moment. This one's for you…",
      "Whispering to the satnav. It listens to me…",
      "Finding somewhere lovely to stop on the way…",
      "Choosing the road with the better sunsets…",
      "Almost ready. Good things are worth the wait…",
      "Plotting. Don't go anywhere…",
      "One more look at the stars, then we go…",
    ],
  },
};

/** The pool of lines for a persona and progress phase, with fallbacks. */
export function linePool(persona, phase) {
  const set = LINES[persona] ?? LINES.standard;
  return set[phase] ?? LINES.standard[phase] ?? LINES.standard.plot;
}
