<script>
  import { onMount } from "svelte";
  import { useListeners } from "./lifecycle.svelte.js";
  import { dataLocationGet,dataLocationChoose,galaxyStatus,voiceInstall,voiceCatalog,voiceStatus,voiceModels,setVoice,voiceUseWindows,voiceServerGet,voiceServerProbe,voiceServerSet,speechEngineStatus,speechEngineInstall,speechEngineStart,onSpeechEngineProgress,personas,setPersona,say,sayNow,voiceInterrupt,getAiConfig,listenStatus,listenConfigSet,listenSetup,listenModelsRemove,audioDevices,pttCapture,onListenSetup,targetKeyStatus,targetTriggerCapture,targetTriggerClear,mapPointsGet,mapPointCapture,mapPointsClear,targetMacroCheck,targetMacroTest,targetMacroEnabledGet,targetMacroEnabledSet,routePlotTest,mapSetupTest,mapSetupSay,mapSetupCancel,mapSetupTarget,gameRouteMaxGet,gameRouteMaxSet , telemetryPrefs, telemetryPrefsSet } from "./api.js";
  let telemetryOn = $state(true);
  onMount(async () => { try { telemetryOn = await telemetryPrefs(); } catch {} });
  import { voiceName, serverVoiceName } from "./voices.js";
  import { KEYS, readKey, writeKey } from "./storage.svelte.js";
  let { finish=()=>{} }=$props();
  const steps=["Welcome","Output voice","Voice input & PTT","Routing control","Route coverage","Galaxy-map interaction","Ready"];
  const spoken=["Welcome to EDDA. First, choose where you want EDDA to keep its data.","Choose how you want your ship computer to sound. Windows voice works immediately, or EDDA can install a local neural voice for you.","Voice input is optional. You can use an activation phrase, push-to-talk, or both.","Choose the control that keeps EDDA routes in step with the game. We recommend the same control you use for Target Next System in Route.","Choose your route coverage. EDDA checks routes against your real jumps and fuel, recalculates when reality disagrees with the plan, and warns about risky non-scoopable targets.","Galaxy-map automation is optional. It lets EDDA open the map, search for a system, and either target one route hop or ask Elite to plot the complete journey. Teach EDDA the four controls it will click, then test both actions on a nearby system.","Setup is complete. Anything you skipped can be configured later."];
  const saved=Math.max(0,Math.min(6,readKey(KEYS.onboardingStep,0)));
  let step=$state(saved),mounted=$state(false);
  // A step is narrated only on its first-ever visit; the set persists so
  // reopening setup later stays quiet on pages already heard. The landing
  // step is NOT pre-seeded — on a fresh install the Welcome page must
  // speak too, and the persisted set already covers genuine revisits.
  const spokenSteps=new Set(readKey(KEYS.onboardingSpoken,[],{json:true}));
  // Switching tabs cuts the current narration instead of queuing behind
  // it: a fresh step barges in with its own line, a revisited one just
  // goes quiet.
  $effect(()=>{writeKey(KEYS.onboardingStep,step); if(mounted){ if(!spokenSteps.has(step)){spokenSteps.add(step);writeKey(KEYS.onboardingSpoken,[...spokenSteps],{json:true});sayNow(spoken[step]).catch(()=>{})} else {voiceInterrupt().catch(()=>{})} }});
  const goStep=(value)=>{message="";step=Math.max(0,Math.min(6,value))};
  const next=()=>goStep(step+1),back=()=>goStep(step-1);
  let dataPath=$state(""),ai=$state(null),message=$state(""),galaxy=$state(null),voiceBusy=$state(false);
  let listen=$state(null),audio=$state(null),setup=$state({}),lcfg=$state({enabled:false,wake_word:"hey edda",ptt:{kind:"none"},model:"parakeet"}),capturingPtt=$state(false);
  let outputVoice=$state(null),installedVoices=$state([]),voiceChoices=$state([]),selectedVoice=$state("en_US-lessac-high.onnx"),personaList=$state([]),selectedPersona=$state("standard");
  const selectedVoiceChoice=$derived(voiceChoices.find(v=>v.model===selectedVoice));
  let serverVoice=$state(null),localEngine=$state("piper"),localEngineBusy=$state(false),localEngineVoices=$state([]),localEngineVoice=$state("af_heart");
  let managedEngines=$state([]),engineProgress=$state(null);
  const managedEngine=$derived(managedEngines.find(e=>e.engine===localEngine));
  let targetKeys=$state({bindings:[],trigger:null}),capturingRoute=$state(false),map=$state(null),capturingMap=$state(null),guidedMap=$state(false),gameRouteMax=$state(1000),routeScale=$state(300);
  const listeners=useListeners();
  const routeTicks=[0,100,500,1000,5000,10000,20000];
  const scaleToLy=x=>{const p=Math.max(0,Math.min(600,Number(x)))/100,i=Math.min(5,Math.floor(p)),f=p-i,a=routeTicks[i],b=routeTicks[i+1];return i===0?Math.round(100*f):Math.round(Math.exp(Math.log(a)+(Math.log(b)-Math.log(a))*f))};
  const lyToScale=v=>{if(v<=100)return v;let j=routeTicks.findIndex(x=>v<=x);if(j<=1)return v;j--;return (j+(Math.log(v)-Math.log(routeTicks[j]))/(Math.log(routeTicks[j+1])-Math.log(routeTicks[j])))*100};
  async function saveRouteScale(){gameRouteMax=await gameRouteMaxSet(scaleToLy(routeScale));routeScale=lyToScale(gameRouteMax)}
  async function setRouteTick(tick){gameRouteMax=await gameRouteMaxSet(tick);routeScale=lyToScale(gameRouteMax)}
  const mapItems=[["search","Search box","the search field at the top-left"],["result","First result","the first system shown after a search"],["target","Target button","targets one EDDA route hop"],["plot","Plot route button","asks Elite to calculate the complete in-game route"]];
  // The teach/test system is the backend's pick: the nearest populated
  // neighbor, so a Colonia resident is never told to plot to the bubble.
  let mapSys=$state("Diso");
  // One setting, two homes (maintainer spec): this checkbox and the identical
  // one in Settings → Routing control both read and write the same flag.
  let macroOn=$state(false);
  onMount(async()=>{try{macroOn=await targetMacroEnabledGet()}catch{}});
  // Fetching the target also puts the name on the clipboard, so refresh
  // it whenever the map step is entered or a run starts: paste, not type.
  const refreshMapTarget=async()=>{try{mapSys=await mapSetupTarget()}catch{}};
  onMount(refreshMapTarget);
  $effect(()=>{if(step===5)refreshMapTarget()});
  const captureInstructions=$derived({search:`Alt-Tab to Elite Dangerous and open the Galaxy Map. Click the Search box for EDDA to record its position, then paste ${mapSys} (it's on your clipboard — Ctrl+V) and search. Return to EDDA without closing the Galaxy Map.`,result:`Return to Elite, click ${mapSys} in the search results for EDDA to record its position, then return to EDDA without closing the Galaxy Map.`,target:`Return to Elite, click the Target button for ${mapSys} so EDDA records its position, then return to EDDA without closing the Galaxy Map.`,plot:`Return to Elite and click the Plot Route button for ${mapSys} so EDDA records its position. Stay in Elite with the Galaxy Map open.`});
  // Item 51: three unchecked boxes (maintainer spec) — nothing downloads
  // without a tick, and all-time implies the 48-hour window.
  async function installVoice(){voiceBusy=true;const choice=voiceChoices.find(v=>v.model===selectedVoice);message=`Downloading and installing ${choice?.label??"the local neural voice"}…`;try{selectedVoice=await voiceInstall(selectedVoice);[installedVoices,voiceChoices,outputVoice]=await Promise.all([voiceModels(),voiceCatalog(),voiceStatus()]);message=`${voiceName(selectedVoice)} installed, selected, and ready.`}catch(e){message=String(e)}finally{voiceBusy=false}}
  async function chooseVoice(e){selectedVoice=e.target.value;if(!selectedVoice)return;try{await setVoice(selectedVoice);outputVoice=await voiceStatus();await say("Voice selected. Systems ready, Commander.");message=`Voice selected: ${voiceName(selectedVoice)}.`}catch(err){message=String(err)}}
  async function choosePersona(e){selectedPersona=e.target.value;try{const p=await setPersona(selectedPersona);selectedPersona=p.selected;message=`Personality selected: ${personaList.find(x=>x.id===selectedPersona)?.name??selectedPersona}.`}catch(err){message=String(err)}}
  const localEngineConfig=()=>({url:serverVoice?.config?.model==="kokoro"?serverVoice.config.url:"http://localhost:8880",model:"kokoro",voice:localEngineVoice||"af_heart",api_key:null});
  async function connectLocalEngine(){localEngineBusy=true;message="Looking for Kokoro on this computer…";try{const cfg=localEngineConfig();localEngineVoices=await voiceServerProbe(cfg);if(localEngineVoices.length&&!localEngineVoices.includes(localEngineVoice))localEngineVoice=localEngineVoices[0];serverVoice=await voiceServerSet(true,{...cfg,voice:localEngineVoice});outputVoice=await voiceStatus();message="Kokoro connected and selected.";await say("Voice selected. Systems ready, Commander.")}catch(e){message=`Kokoro is not running at ${localEngineConfig().url}. Start its local engine, then press Connect again. ${String(e)}`}finally{localEngineBusy=false}}
  async function refreshManagedVoice(){managedEngines=await speechEngineStatus();serverVoice=await voiceServerGet();outputVoice=await voiceStatus();const cfg=serverVoice?.config??localEngineConfig();localEngineVoices=await voiceServerProbe(cfg);if(localEngineVoices.length&&!localEngineVoices.includes(localEngineVoice))localEngineVoice=localEngineVoices[0];}
  async function chooseKokoro(){localEngine="kokoro";localEngineVoice=serverVoice?.config?.voice??"af_heart";if(managedEngines.find(e=>e.engine==="kokoro")?.running){try{await refreshManagedVoice()}catch(e){message=String(e)}}}
  async function installManagedEngine(){localEngineBusy=true;engineProgress=null;message="Installing Kokoro in your EDDA data folder…";try{await speechEngineInstall(localEngine);await refreshManagedVoice();message="Kokoro installed, running, and selected.";await say("Kokoro is installed and ready, Commander.")}catch(e){message=String(e)}finally{localEngineBusy=false}}
  async function startManagedEngine(){localEngineBusy=true;try{await speechEngineStart(localEngine);await refreshManagedVoice();message="Kokoro running and selected."}catch(e){message=String(e)}finally{localEngineBusy=false}}
  async function useWindows(){localEngine="windows";try{outputVoice=await voiceUseWindows();message="Windows voice selected. No local model or helper process is required."}catch(e){message=String(e)}}
  async function installRecognition(){message="Preparing voice recognition…";try{await listenSetup("parakeet",!!lcfg.wake_word)}catch(e){message=String(e)}}
  async function removeRecognition(){if(!confirm("Remove Parakeet, the command model, and their recognition runtimes? Voice output and your control preferences will be kept."))return;message="Removing downloaded recognition models…";try{await listenModelsRemove();listen=await listenStatus();setup={};message="Downloaded recognition models removed."}catch(e){message=String(e)}}
  async function capturePttControl(){capturingPtt=true;message="Press the keyboard, joystick, or throttle control you want to hold while speaking.";try{lcfg.ptt=await pttCapture(10);await applyVoiceInput();message=`Captured ${lcfg.ptt.name??lcfg.ptt.hotkey??"control"} and saved.`}catch(e){message=String(e)}finally{capturingPtt=false}}
  // Every control on this step applies immediately; installed models are
  // standing intent, so voice input enables itself once they are ready.
  async function applyVoiceInput(enable=false){try{lcfg.model="parakeet";if(enable||(listen?.parakeet_ready&&listen?.ready))lcfg.enabled=true;lcfg=await listenConfigSet(lcfg)}catch(e){message=String(e)}}
  async function captureRoute(){capturingRoute=true;message="Press the control you use in Elite for Target Next System in Route.";try{targetKeys=await targetTriggerCapture();message="Routing control captured and ready."}catch(e){message=String(e)}finally{capturingRoute=false}}
  // Map-flow failures are SPOKEN as well as shown: during these steps the
  // commander is alt-tabbed into Elite, and an error that only lands in
  // the setup window reads as a stall (field case 2026-09-04).
  const mapFailure=(e)=>{const text=String(e);message=text;sayNow(text).catch(()=>{})};
  async function capturePoint(which){capturingMap=which;message=`${captureInstructions[which]} You have 30 seconds.`;say(captureInstructions[which]).catch(()=>{});try{map=await mapPointCapture(which);if(which==="plot"&&map?.search&&map?.result&&map?.target&&map?.plot){const check=await targetMacroCheck();if(!check.ok){const problems=check.steps.filter(s=>!s.bound).map(s=>s.note??`${s.action} is not usable`).join(" ");throw new Error(`Galaxy Map automation needs usable keyboard bindings before it can be tested. ${problems}`)}message="Galaxy Map controls captured. Running the guided test…";message=await mapSetupTest()}else message="Position captured. Return to Setup when ready."}catch(e){mapFailure(e)}finally{if(which==="plot")await mapSetupCancel().catch(()=>{});capturingMap=null}}
  async function guidedMapSetup(){guidedMap=true;message="Guided Galaxy Map setup underway. Follow EDDA's prompts in Elite.";await refreshMapTarget();const prompts={search:"Open the Galaxy Map, then click the Search box.",result:`I put ${mapSys} on your clipboard. Paste it into the search with Control V, then click the first ${mapSys} result.`,target:"Click the Target button.",plot:"Click the Plot Route button."};try{await mapSetupSay("Galaxy Map setup underway. Alt-tab to Elite, and follow the prompts.");for(const [which] of mapItems){capturingMap=which;await mapSetupSay(prompts[which]);map=await mapPointCapture(which)}const check=await targetMacroCheck();if(!check.ok){const problems=check.steps.filter(s=>!s.bound).map(s=>s.note??`${s.action} is not usable`).join(" ");throw new Error(`Galaxy Map automation needs usable keyboard bindings before it can be tested. ${problems}`)}message=await mapSetupTest()}catch(e){mapFailure(e)}finally{await mapSetupCancel().catch(()=>{});capturingMap=null;guidedMap=false}}
  async function testMap(){message=`Switch to Elite now. EDDA will test targeting ${mapSys} after three seconds.`;await new Promise(r=>setTimeout(r,3000));try{message=await targetMacroTest()}catch(e){mapFailure(e)}}
  async function testPlot(){message=`Switch to Elite now. EDDA will test Plot Route for ${mapSys} after three seconds.`;await new Promise(r=>setTimeout(r,3000));try{message=await routePlotTest(mapSys)}catch(e){mapFailure(e)}}
  const setupLine=(key,label)=>{const x=setup[key];return x?`${label} — ${x.status}${x.bytes?` · ${(x.bytes/1048576).toFixed(0)}${x.total?` / ${(x.total/1048576).toFixed(0)}`:""} MB`:""}`:null};
  onMount(async()=>{mounted=true;try{dataPath=await dataLocationGet()}catch{}try{ai=await getAiConfig()}catch{}try{galaxy=await galaxyStatus()}catch{}try{outputVoice=await voiceStatus();[installedVoices,voiceChoices,serverVoice,managedEngines]=await Promise.all([voiceModels(),voiceCatalog(),voiceServerGet(),speechEngineStatus()]);selectedVoice=installedVoices.find(v=>outputVoice?.model&&v.startsWith(outputVoice.model))??selectedVoice;localEngine=outputVoice?.backend==="sapi"?"windows":outputVoice?.backend==="piper"?"piper":localEngine;if(serverVoice?.enabled){localEngine="kokoro";localEngineVoice=serverVoice.config?.voice??localEngineVoice;localEngineVoices=serverVoice.voices??[]}const p=await personas();personaList=p.personas;selectedPersona=p.selected}catch{}try{listen=await listenStatus();lcfg={...lcfg,...listen.config,model:"parakeet"};audio=await audioDevices()}catch{}try{targetKeys=await targetKeyStatus()}catch{}try{map=await mapPointsGet()}catch{}listeners.add(onSpeechEngineProgress(e=>engineProgress=e.payload));listeners.add(onListenSetup(async e=>{if(e.payload.phase==="done"){setup={};if(e.payload.status==="ok"){try{listen=await listenStatus()}catch{}await applyVoiceInput(true);message="Voice recognition is ready and listening."}else message=`Voice setup failed: ${e.payload.error}`}else setup={...setup,[e.payload.phase]:e.payload}}))});
  onMount(()=>{let attempts=0;const timer=setInterval(async()=>{if(++attempts>20||localEngineVoices.length){clearInterval(timer);return}if(localEngine==="kokoro"&&managedEngines.some(e=>e.engine==="kokoro"&&e.running)){try{await refreshManagedVoice()}catch{}}},1000);return()=>clearInterval(timer)});
  onMount(async()=>{try{gameRouteMax=await gameRouteMaxGet();routeScale=lyToScale(gameRouteMax)}catch{}});
</script>

<section class="panel wizard" style="width:100%;max-width:none;margin:0;flex:0 0 auto">
 <div class="progress">{#each steps as name,i}<button class:active={i===step} class:done={i<step} onclick={()=>goStep(i)} aria-label={`Step ${i+1}: ${name}`}>{i+1}</button>{/each}</div><p class="eyebrow">First-run setup · step {step+1} of 7</p>
 {#if step===0}<h2>Welcome to EDDA</h2><p>Set up only what you want. You can skip anything and return later.</p><div class="choice"><div><b>Data folder</b><small>{dataPath}</small></div><button onclick={dataLocationChoose}>Choose data folder</button></div><p class="muted small">Changing it restarts EDDA before anything large is downloaded.</p>{#if ai?.has_key}<div class="notice"><b>Saved Claude credential found</b><br><span class="small">Windows Credential Manager retained an EDDA API key from an earlier installation. Setup will not erase it; you can review or replace it later.</span></div>{/if}
 {:else if step===1}<h2>Choose how EDDA speaks</h2><p>Voice controls how EDDA sounds; personality controls how she phrases things. All neural choices below run locally on this computer.</p><div class="engine-tabs"><button class:on={localEngine==="windows"} class="ghost" onclick={useWindows}>Windows voice</button><button class:on={localEngine==="piper"} class="ghost" onclick={()=>localEngine="piper"}>Piper inside EDDA</button><button class:on={localEngine==="kokoro"} class="ghost" onclick={chooseKokoro}>Kokoro local engine</button></div>{#if localEngine==="windows"}<div class="notice good"><b>Windows voice selected</b><br><span class="small">Ready immediately. No model download or helper process.</span></div>{:else if localEngine==="piper"}{#if installedVoices.length}<div class="notice good"><b>Local neural voice installed</b></div>{/if}<div class="choice"><label>Piper voice <select bind:value={selectedVoice} onchange={e=>{if(voiceChoices.find(v=>v.model===e.target.value)?.installed)chooseVoice(e)}}>{#each voiceChoices as v}<option value={v.model}>{v.label} · {v.size_mb} MB{v.installed?" · installed":""}</option>{/each}</select></label>{#if !selectedVoiceChoice?.installed}<button onclick={installVoice} disabled={voiceBusy}>{voiceBusy?"Downloading…":`Download ${selectedVoiceChoice?.label??"voice"}`}</button>{/if}</div>{:else}<div class="choice"><div><b>Kokoro</b><small>{managedEngine?.note}</small><small>{managedEngine?.approximate_mb?.toLocaleString()} MB approximate download and installed runtime · stored in {dataPath}</small></div>{#if managedEngine?.running}<span class="pill ok">running</span>{:else if managedEngine?.installed}<button onclick={startManagedEngine} disabled={localEngineBusy}>{localEngineBusy?"Starting…":"Start and use"}</button>{:else}<button onclick={installManagedEngine} disabled={localEngineBusy||!managedEngine?.available}>{localEngineBusy?"Installing…":managedEngine?.available?"Download and install":"Not available yet"}</button>{/if}</div>{#if engineProgress?.engine===localEngine}<p class="download">{engineProgress.detail}</p>{/if}{#if localEngineVoices.length}<label class="row" style="margin-top:.6rem">Voice <select bind:value={localEngineVoice} onchange={connectLocalEngine}>{#each localEngineVoices as v}<option value={v}>{serverVoiceName(v)}</option>{/each}</select></label>{/if}{/if}<div class="row" style="margin-top:.7rem"><label>Personality <select value={selectedPersona} onchange={choosePersona}>{#each personaList as p}<option value={p.id}>{p.name} — {p.blurb}</option>{/each}</select></label></div>
 {:else if step===2}<h2>Optional voice input and push-to-talk</h2><p>Parakeet accurately transcribes natural questions and varied wording. A small companion model handles the activation phrase and immediate cockpit commands.</p><label>Microphone <select bind:value={lcfg.mic_device} onchange={()=>applyVoiceInput()}><option value={null}>System default</option>{#each audio?.inputs??[] as d}<option value={d}>{d}</option>{/each}</select></label><label class="row"><input type="checkbox" checked={!!lcfg.wake_word} onchange={e=>{lcfg.wake_word=e.target.checked?"hey edda":"";applyVoiceInput()}}/> Use “Hey EDDA” activation phrase</label><div class="row"><button onclick={capturePttControl} disabled={capturingPtt}>{capturingPtt?"Press it now…":"Capture push-to-talk control"}</button>{#if lcfg.ptt?.kind&&lcfg.ptt.kind!=="none"}<span class="pill ok">{lcfg.ptt.name??lcfg.ptt.hotkey??"captured"}</span>{/if}</div>{#if listen?.parakeet_ready&&listen?.ready}<div class="notice good"><b>Parakeet and command model ready</b><br><span class="small">Natural speech, activation phrase, and cockpit commands are available locally.</span></div>{:else}<button onclick={installRecognition} disabled={listen?.setup_running}>Download Parakeet + command model</button>{/if}{#if setupLine("wake-word model","Command model")}<p class="download">{setupLine("wake-word model","Command model")}</p>{/if}{#if setupLine("Parakeet model (460 MB)","Parakeet")}<p class="download">{setupLine("Parakeet model (460 MB)","Parakeet")}</p>{/if}
 {#if listen?.parakeet_ready&&listen?.ready}<button class="ghost" onclick={removeRecognition}>Remove downloaded recognition models</button>{/if}
 {:else if step===3}<h2>Keep routes in step with Elite</h2><p>Say <b>“Guidance, target next”</b> to target the next stop. For one-button use, capture the same control you use in Elite for <b>Target Next System in Route</b>.</p><button onclick={captureRoute} disabled={capturingRoute}>{capturingRoute?"Press it now…":targetKeys.trigger?"Change captured control":"Capture routing control"}</button>{#if targetKeys.trigger}<span class="pill ok">{targetKeys.trigger.name??targetKeys.trigger.hotkey??"captured"}</span><button class="ghost" onclick={async()=>targetKeys=await targetTriggerClear()}>Forget</button>{/if}
 {:else if step===4}<h2>Choose your route coverage</h2><p>Use Elite's fast in-game planner for nearby destinations. EDDA's route planning on the community API adds route analysis for longer journeys.</p><div class="notice good"><b>Adaptive route safety</b><br><span class="small">EDDA checks real jumps and current fuel against the plan. It automatically recalculates after a detour, ship change, or impossible fuel schedule, and warns when a low-fuel target cannot be scooped.</span></div><div style="max-width:700px;margin:1.2rem 0"><div style="display:flex;justify-content:space-between;align-items:baseline;gap:1rem"><b>Use in-game routing for trips up to</b><output class="pill accent">{gameRouteMax.toLocaleString()} ly</output></div><input aria-label="Maximum distance for in-game routing" style="display:block;width:100%;margin:.8rem 0 .2rem" type="range" min="0" max="600" step="1" bind:value={routeScale} oninput={()=>gameRouteMax=scaleToLy(routeScale)} onchange={saveRouteScale}/><div style="position:relative;height:1.7rem;margin:0 .5rem">{#each routeTicks as tick,i}<button class="ghost" style={`position:absolute;left:${i*100/(routeTicks.length-1)}%;transform:${i===0?'none':i===routeTicks.length-1?'translateX(-100%)':'translateX(-50%)'};border:0;padding:.15rem .25rem;margin:0;font-size:.72rem;white-space:nowrap`} onclick={()=>setRouteTick(tick)} aria-label={`Set in-game routing to ${tick.toLocaleString()} light-years`}>{tick.toLocaleString()}</button>{/each}</div></div><p class="muted small">Choose 0 to always use EDDA's planner.</p>{#if galaxy?.available}<span class="pill ok">Route index ready{galaxy.populated_only?" (bubble and Colonia)":""}</span>{/if}
 {:else if step===5}<h2>Optional galaxy-map automation</h2><p>When you target a destination, EDDA will open the Galaxy Map, paste the system name into Search, and select the first result. It will then click <b>Target</b> for one hop on an EDDA route, or <b>Plot Route</b> when Elite should calculate the complete journey.</p><label class="row" style="margin:.6rem 0"><input type="checkbox" bind:checked={macroOn} onchange={(e)=>targetMacroEnabledSet(e.target.checked)}/> <b>Enable EDDA routing control</b></label><p>Use the guided setup to stay in Elite while EDDA speaks and displays each instruction in the HUD. The individual controls remain available if one position needs to be repaired.</p><button onclick={guidedMapSetup} disabled={guidedMap||capturingMap!==null}>{guidedMap?"Guided setup underway…":"Begin guided Galaxy Map setup"}</button><ol class="captures">{#each mapItems as item,i}<li><b>{i+1}. {item[1]}</b><span class="muted small">{item[2]}</span>{#if map?.[item[0]]}<span class="pill ok">taught</span>{/if}<button onclick={()=>capturePoint(item[0])} disabled={guidedMap||capturingMap!==null}>{capturingMap===item[0]?"Click it in Elite…":"Capture"}</button></li>{/each}</ol>{#if map?.search&&map?.result&&map?.target&&map?.plot}<div class="notice good"><b>Galaxy Map controls ready</b><br><span class="small">The guided setup verifies targeting and route plotting automatically. Use these controls to repeat either test.</span></div><div class="row"><button onclick={testMap} disabled={guidedMap}>Test targeting {mapSys}</button><button onclick={testPlot} disabled={guidedMap}>Test plotting a route to {mapSys}</button><button class="ghost" disabled={guidedMap} onclick={async()=>map=await mapPointsClear()}>Start over</button></div>{/if}
 {:else}<h2>EDDA is ready</h2><p>Background processing will announce itself in the HUD and by voice when each capability becomes available.</p><p class="muted small">EDDA, with your consent, will collect anonymous data to improve the app. You can see exactly what data EDDA collects <a href="https://edda-app.com/privacy/" target="_blank" rel="noreferrer">here</a>.</p><label class="row"><input type="checkbox" checked={telemetryOn} onchange={(e)=>{telemetryOn=e.currentTarget.checked;telemetryPrefsSet(telemetryOn).catch(()=>{})}}/> Send anonymous usage data</label><button onclick={finish}>Finish setup</button>{/if}
 {#if message}<p class="message">{message}</p>{/if}<footer><button class="ghost" onclick={back} disabled={step===0}>Back</button>{#if step<6}<button onclick={next}>Next</button>{/if}</footer>
</section>
<style>.wizard{max-width:900px;margin:1rem auto;padding:1.4rem}.wizard h2{margin:.25rem 0 .7rem;font-size:1.35rem}.wizard p{line-height:1.5}.eyebrow{color:var(--accent);text-transform:uppercase;letter-spacing:.08em;font-size:.72rem}.progress{display:flex;gap:.55rem;margin-bottom:1rem}.progress button{width:2rem;height:2rem;padding:0;border-radius:50%;background:transparent;color:var(--muted)}.progress button.active{color:var(--bg);background:var(--accent);border-color:var(--accent)}.progress button.done{color:var(--accent);border-color:var(--accent)}.notice{padding:.8rem;border:1px solid var(--line);border-radius:6px;background:var(--panel-2);margin:.8rem 0}.notice.good{border-color:#57c66d66}.message{color:var(--accent-2);font-size:.85rem}.choice,.row{display:flex;align-items:center;gap:.6rem;flex-wrap:wrap}.choice{justify-content:space-between;padding:.8rem;border:1px solid var(--line);border-radius:6px}.choice small{display:block;color:var(--muted);margin-top:.2rem}.download{margin:.25rem 0;font-size:.82rem}.captures{padding:0;list-style:none}.captures li{display:grid;grid-template-columns:10rem 1fr auto auto;gap:.6rem;align-items:center;padding:.45rem 0;border-bottom:1px solid var(--line)}footer{display:flex;justify-content:space-between;margin-top:1.2rem;border-top:1px solid var(--line);padding-top:.8rem}@media(max-width:700px){.captures li{grid-template-columns:1fr}.choice{align-items:flex-start}}</style>
